version: '3'

services: 
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - 4001:4000
        volumes: 
            - .:/home/app-user
            
            


